version: '3.8'

services:
  # -------------------------
  # Course DB
  # -------------------------
  course-db:
    image: postgres:15
    container_name: course-db
    environment:
      POSTGRES_DB: course
      POSTGRES_USER: course
      POSTGRES_PASSWORD: course
    ports:
      - "5433:5432"  
    volumes:
      - course-data:/var/lib/postgresql/data

  # -------------------------
  # Course Service
  # -------------------------
  course-service:
    build: ./elearning-course-service
    container_name: elearning-course-service
    depends_on:
      - course-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://course-db:5432/course
      SPRING_DATASOURCE_USERNAME: course
      SPRING_DATASOURCE_PASSWORD: course
    ports:
      - "8080:8080"

  # -------------------------
  # Student DB
  # -------------------------
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5434:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

  # -------------------------
  # Student Service
  # -------------------------
  user-service:
    build: ./elearning-user-service
    container_name: elearning-user-service
    depends_on:
      - user-db
      - keycloak
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/realms/elearning
      KEYCLOAK_REALM: elearning
      KEYCLOAK_RESOURCE: user-service
      KEYCLOAK_PUBLIC_CLIENT: true
      KEYCLOAK_CLIENT_SECRET: user-service-secret-key
    ports:
      - "8081:8080"
  # -------------------------
  # Enrollment DB
  # -------------------------
  enrollment-db:
    image: postgres:15
    container_name: enrollment-db
    environment:
      POSTGRES_DB: enrollment
      POSTGRES_USER: enrollment
      POSTGRES_PASSWORD: enrollment
    ports:
      - "5435:5432"
    volumes:
      - enrollment-data:/var/lib/postgresql/data

  # -------------------------
  # Enrollment Service
  # -------------------------
  enrollment-service:
    build: ./elearning-enrollment-service
    container_name: elearning-enrollment-service
    depends_on:
      - enrollment-db
      - keycloak
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://enrollment-db:5432/enrollment
      SPRING_DATASOURCE_USERNAME: enrollment
      SPRING_DATASOURCE_PASSWORD: enrollment
    ports:
      - "8082:8080"

  # -------------------------
  # Keycloak
  # -------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    volumes:
      - ./elearning-keycloak/keycloak.json:/opt/keycloak/data/import/realm.json
    ports:
      - "9000:8080"
    depends_on:
      - keycloak-db

  # -------------------------
  # Keycloak DB
  # -------------------------
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data


# -------------------------
# Volumes
# -------------------------
volumes:
  course-data:
  user-data:
  enrollment-data:
  keycloak-data:

